### ISSUE TITLE
您好，软件bug，解压后的路径应该为“”原输出路径+解压后的文件夹+数据文件名”，您的软件少了个“解压后的文件夹”的名称

### ISSUE THREAD

**Issue by SMYUCAS** [GenghisYoung233/Gaofen-Batch#5]
您好，软件bug，解压后的路径应该为“”原输出路径+解压后的文件夹+数据文件名”，您的软件少了个“解压后的文件夹”的名称，我想从源码直接编译您的程序一直出问题（我小菜鸡一个），能否重新发布个正确的release版本的软件呢？如果方便的话，大佬可以加上我的微信17550055985，十分感谢
<img width="920" alt="image" src="https://github.com/GenghisYoung233/Gaofen-Batch/assets/114888799/a6c174ed-f7c9-4eb0-9038-929b4f6828c4">

**Comment by GenghisYoung233** [comment]
抱歉，来晚了。从截图上看，问题可能是出在上一步‘RPC校正‘上，GDAL没有将RPC校正的结果输出到 D:/Test/res/GF6_PMS_E122.1_N47.6_20240113_L1A1420405783-MUX.tiff，导致图中的报错。如果正常运行，应该在 ’解压后路径‘ 同时看到 ’解压后的文件夹‘ 和 ’数据文件名‘。如下图所示。

![image](https://github.com/GenghisYoung233/Gaofen-Batch/assets/63275197/0c29c102-87ad-4bbc-96e4-1afa628a36a9)

方便的话，请提供完整的日志和压缩包内文件构成截图。

**Comment by SMYUCAS** [comment]
1.输入
<img width="763" alt="image" src="https://github.com/GenghisYoung233/Gaofen-Batch/assets/114888799/7fb681e0-946e-45b9-9cff-31f8edaaca94">
<img width="624" alt="image" src="https://github.com/GenghisYoung233/Gaofen-Batch/assets/114888799/72afc044-fb40-4e17-aa62-3afae285ebb8">

2.输出
<img width="770" alt="image" src="https://github.com/GenghisYoung233/Gaofen-Batch/assets/114888799/beb3dcbb-3a93-455a-9e52-5fe22cb25af3">
3.报错
<img width="1280" alt="image" src="https://github.com/GenghisYoung233/Gaofen-Batch/assets/114888799/3735d927-5804-4509-b4e5-32c0de2736ea">
<img width="1285" alt="image" src="https://github.com/GenghisYoung233/Gaofen-Batch/assets/114888799/49fcc65a-094d-4531-99cc-506ec501a690">

**Comment by GenghisYoung233** [comment]
操作步骤没有问题，文件结构也没有变化。麻烦提供日志区完整的输出信息，从’启动服务‘到最后的’Child process exited with code 1‘。

**Comment by SMYUCAS** [comment]
启动服务（2024/1/23 13:50:08）
Gaofen-Batch, streamlines raster preprocessing of China-made satellite. Powered by GDAL and Electron.
2024-01-23 13:50:32.155 | WARNING  | __main__:main:282 - 处理第1景数据中，共1景数据

2024-01-23 13:50:32.155 | INFO     | __main__:main:283 - Processing D:\SAR_Missions\2024\10-gf6\GF6_PMS_E133.5_N48.3_20231127_L1A1420379632.tar.gz
2024-01-23 13:50:32.155 | INFO     | __main__:untar:27 - 解压中...

2024-01-23 13:51:07.220 | INFO     | __main__:main:300 - 处理多光谱数据中...

2024-01-23 13:51:07.220 | INFO     | __main__:rpc_ortho:54 - RPC正射校正中...

ERROR 1: PROJ: proj_create_from_database: Open of C:\Users\宋明阳\Desktop\GaofenBatch\bin\OTB-8.1.2-Win64\share\proj\proj.db failed
ERROR 1: Translating source or target SRS failed:
EPSG:32653

Usage: gdalwarp [--help-general] [--formats]
    [-s_srs srs_def] [-t_srs srs_def] [-to "NAME=VALUE"]* [-novshiftgrid]
    [-order n | -tps | -rpc | -geoloc] [-et err_threshold]
    [-refine_gcps tolerance [minimum_gcps]]
    [-te xmin ymin xmax ymax] [-tr xres yres] [-tap] [-ts width height]
    [-ovr level|AUTO|AUTO-n|NONE] [-wo "NAME=VALUE"] [-ot Byte/Int16/...] [-wt Byte/Int16]
    [-srcnodata "value [value...]"] [-dstnodata "value [value...]"] -dstalpha
    [-r resampling_method] [-wm memory_in_mb] [-multi] [-q]
    [-cutline datasource] [-cl layer] [-cwhere expression]
    [-csql statement] [-cblend dist_in_pixels] [-crop_to_cutline]
    [-if format]* [-of format] [-co "NAME=VALUE"]* [-overwrite]
    [-nomd] [-cvmd meta_conflict_value] [-setci] [-oo NAME=VALUE]*
    [-doo NAME=VALUE]*
    srcfile* dstfile

Available resampling methods:
    near (default), bilinear, cubic, cubicspline, lanczos, average, mode,  max, min, med, Q1, Q3, sum.

Traceback (most recent call last):
  File "rasterio\_base.pyx", line 310, in rasterio._base.DatasetBase.__init__

  File "rasterio\_base.pyx", line 221, in rasterio._base.open_dataset
  File "rasterio\_err.pyx", line 221, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: D:/SAR_Missions/2024/10-gf6/Test/GF6_PMS_E133.5_N48.3_20231127_L1A1420379632-MUX.tiff: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 426, in <module>
  File "main.py", line 340, in main
  File "main.py", line 312, in ato_cor
  File "main.py", line 186, in apply_corrections
  File "rasterio\env.py", line 451, in wrapper
  File "rasterio\__init__.py", line 319, in open
  File "rasterio\_base.pyx", line 312, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: D:/SAR_Missions/2024/10-gf6/Test/GF6_PMS_E133.5_N48.3_20231127_L1A1420379632-MUX.tiff: No such file or directory
[30272] Fail
ed to execute script 'main' due to unhandled exception!

Child process exited with code 1

**Comment by GenghisYoung233** [comment]
把 GaofenBatch 文件夹复制到纯英文路径下试试，Orfeo Toolbox（OTB）不识别中文路径
